# Generated by Django 5.1.5 on 2025-06-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Migrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('region_id', models.IntegerField(verbose_name='Region ID')),
                ('district_id', models.IntegerField(verbose_name='District ID')),
                ('pinfl', models.CharField(max_length=14, unique=True, verbose_name='PINFL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Migrant',
                'verbose_name_plural': 'Migrants',
                'ordering': ['-created_at'],
            },
        ),
    ]
