# Generated by Django 5.1.5 on 2025-06-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='migrant',
            table='migrant',
        ),
    ]
