# Generated by Django 5.1.5 on 2025-06-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0002_alter_migrant_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrant',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='migrant',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, verbose_name='Gender'),
        ),
    ]
