# Generated by Django 5.1.5 on 2025-06-19 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant', '0003_migrant_birth_date_migrant_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
