# Generated by Django 5.1.5 on 2025-06-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorderCross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(verbose_name='Registration Date')),
                ('endpoint_id', models.IntegerField(verbose_name='Endpoint ID')),
                ('direction_type_code', models.CharField(max_length=10, verbose_name='Direction Type Code')),
                ('migrant_id', models.IntegerField(verbose_name='Migrant ID')),
                ('trip_purpose_id', models.IntegerField(verbose_name='Trip Purpose ID')),
                ('driection_country_id', models.IntegerField(verbose_name='Direction Country ID')),
                ('transport_type_code_id', models.IntegerField(verbose_name='Transport Type Code ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Border Cross',
                'verbose_name_plural': 'Border Crosses',
                'ordering': ['-created_at'],
            },
        ),
    ]
