# Generated by Django 5.1.5 on 2025-06-19 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0002_alter_bordercross_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordercross',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
